VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "GM_clCores"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Attribute VB_Ext_KEY = "SavedWithClassBuilder6" ,"Yes"
Attribute VB_Ext_KEY = "Top_Level" ,"Yes"
Public Enum GM_enCOR
    GM_Cor_Branca = &HFFFFFF
    
    GM_Cor_Amarela = &HFFFF&
    GM_Cor_AmarelaBebê = &HC0FFFF
    
    GM_Cor_Rosa = &HFF00FF
    GM_Cor_RosaBebê = &HFFC0FF
    GM_Cor_RosaEscura = &HC000C0
    
    GM_Cor_Vermelha = &HFF&
    GM_Cor_VermelhaBebê = &HC0C0FF
    GM_Cor_VermelhaEscura = &HC0&
    
    GM_Cor_Cinza = &HC0C0C0
    GM_Cor_CinzaEscura = &H808080
    GM_Cor_Preta = &H0&
    
    GM_Cor_Azul = &HFF0000
    GM_Cor_AzulBebê = &HFFFFC0
    GM_Cor_AzulClaro = &HFFFF80
    GM_Cor_AzulEscuro = &HC00000
    GM_Cor_AzulMarinho = &H800000
        
    GM_Cor_Verde = &HC000&
    GM_Cor_VerdeBebê = &HC0FFC0
    GM_Cor_VerdeEscura = &H8000&
    
    GM_Cor_Laranja = &H80FF&
    GM_Cor_LaranjaBebê = &HC0E0FF
    
    GM_Cor_BotõesFace = &H8000000F
    GM_Cor_AreaDeTrabalho = &H80000001
    
    
End Enum

